(function(global){
"use strict";
const PT_BR_SERVICES=Object.freeze({"vehicle_inspection":"Vistoria veicular","suspension":"Suspensão","engine":"Motor","brakes":"Freios","steering":"Direção","vehicle_electrical":"Elétrica automotiva","air_conditioning":"Ar-condicionado","panel":"Painel elétrico","electric_motor":"Motor elétrico","thermography":"Termografia","installation":"Instalação elétrica","grounding":"Aterramento","grounding_equipotentialization":"Aterramento e Equipotencialização","lighting":"Iluminação","eletrica_tupy":"ATIVIDADES ROTINEIRAS TUPY","machine":"Máquina","pipeline":"Tubulação","structure":"Estrutura","tank":"Tanque","basic_wash":"Lavação simples","complete_wash":"Lavação completa","technical_wash":"Lavação técnica","interior_detailing":"Higienização interna","polishing":"Polimento","paint_protection":"Proteção da pintura","sofa_cleaning":"Sofá","mattress_cleaning":"Colchão","armchair_cleaning":"Poltrona","chair_cleaning":"Cadeiras","auto_upholstery":"Banco automotivo","carpet_cleaning":"Tapete e carpete","curtain_installation":"Instalação de cortina","blind_installation":"Instalação de persiana","curtain_maintenance":"Manutenção de cortina","blind_maintenance":"Manutenção de persiana","motorized_system":"Sistema motorizado","track_and_rod":"Trilho e varão","small_repairs":"Pequenos reparos","masonry":"Alvenaria","painting":"Pintura","flooring":"Pisos e revestimentos","minor_renovation":"Pequena reforma","general_maintenance":"Manutenção geral","common_areas":"Áreas comuns","electrical_system":"Sistema elétrico","hydraulic_system":"Sistema hidráulico","pump_room":"Bombas e casa de máquinas","elevators":"Elevadores","fire_safety":"Sistema de incêndio","facade_roof":"Fachada e cobertura","garage":"Garagem","access_gates":"Portões e acessos","leisure_area":"Piscina e área de lazer","maintenance_occurrences":"Ocorrências e manutenção","roof":"Telhado","facade":"Fachada","tower":"Torre","solar":"Usina solar"});
const PT_BR_PROFILES=Object.freeze({"workshop":"Oficina mecânica","electrical":"Elétrica","industrial":"Industrial","car_wash":"Lavação automotiva","upholstery_cleaning":"Higienização de estofados","curtains_blinds":"Cortinas e persianas","repairs_maintenance":"Reparos e manutenção","condominiums":"Condomínios","drone":"Drone","vehicle_inspection":"Vistoria veicular","grounding_equipotentialization":"Aterramento e Equipotencialização"});
function clean(v){return String(v==null?"":v).trim();}
function humanize(id){return clean(id).replace(/[_-]+/g," ").replace(/\b\w/g,c=>c.toUpperCase());}
function serviceLabel(id,fallback){const key=clean(id).toLowerCase();return PT_BR_SERVICES[key]||clean(fallback)||humanize(key)||"Atendimento";}
function profileLabel(id,fallback){const key=clean(id).toLowerCase();return PT_BR_PROFILES[key]||clean(fallback)||humanize(key)||"Aurora";}
global.AuroraI18n=Object.freeze({locale:"pt-BR",serviceLabel,profileLabel,serviceLabels:PT_BR_SERVICES,profileLabels:PT_BR_PROFILES});
})(window);
