(function(global){
'use strict';
const BUILD='AURORA V47 RC1 R29 OFFLINE PERSISTENCE SCREEN DIAG';
const state={event:'BOOT',caseId:'-',repo:'-',reread:'-',field:'-',photo:'-',link:'-',draft:'-',storage:'-',error:'-',seq:0};
let previousCase=null;
function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(_){return null;}}
function short(v,n=42){let s=String(v==null?'':v).replace(/\s+/g,' ').trim();return s.length>n?s.slice(0,n)+'…':s;}
function storageInfo(){let chars=0, aurora=0;try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||'';const v=localStorage.getItem(k)||'';chars+=k.length+v.length;if(/^aurora/i.test(k)||/^AURORA/.test(k))aurora+=k.length+v.length;}return `OK ${(chars*2/1048576).toFixed(2)}MB (Aurora ${(aurora*2/1048576).toFixed(2)}MB)`;}catch(e){return 'ERRO '+short(e.name||e.message);}}
function meaningfulDiff(a,b,path='',out=[]){if(out.length>=3)return out;if(a===b)return out;const ta=typeof a,tb=typeof b;if(a==null||b==null||ta!=='object'||tb!=='object'){if(!/(updated_at|saved_at|created_at|last_|timestamp)/i.test(path))out.push(`${path||'valor'}=${short(b)}`);return out;}const keys=new Set([...Object.keys(a||{}),...Object.keys(b||{})]);for(const k of keys){if(out.length>=3)break;if(/^(updated_at|saved_at|created_at|last_|timestamp)/i.test(k))continue;meaningfulDiff(a&&a[k],b&&b[k],path?path+'.'+k:k,out);}return out;}
function render(){let el=document.getElementById('aurora-offline-diag-r29');if(!el){el=document.createElement('div');el.id='aurora-offline-diag-r29';el.innerHTML='<div class="r29h">DIAGNÓSTICO OFFLINE R29 <button type="button">×</button></div><pre></pre>';document.body.appendChild(el);const st=document.createElement('style');st.textContent=`#aurora-offline-diag-r29{position:fixed;z-index:2147483647;left:8px;right:8px;top:92px;max-width:720px;margin:auto;background:rgba(3,12,25,.96);color:#e8f4ff;border:2px solid #5ce1e6;border-radius:12px;padding:10px 12px;font:12px/1.35 monospace;box-shadow:0 8px 28px #0008}#aurora-offline-diag-r29 .r29h{font:bold 13px sans-serif;color:#5ce1e6;display:flex;justify-content:space-between}#aurora-offline-diag-r29 button{background:none;border:0;color:#fff;font-size:18px}#aurora-offline-diag-r29 pre{white-space:pre-wrap;margin:7px 0 0;max-height:255px;overflow:auto}`;document.head.appendChild(st);el.querySelector('button').onclick=()=>{el.style.display='none';};}
const pre=el.querySelector('pre');if(pre)pre.textContent=[`REDE: ${navigator.onLine?'ONLINE':'OFFLINE'}   EVENTO #${state.seq}: ${state.event}`,`CASE ID: ${state.caseId}`,`CAMPO: ${state.field}`,`SALVAR CASE: ${state.repo}`,`RELEITURA IMEDIATA: ${state.reread}`,`FOTO INDEXEDDB: ${state.photo}`,`FOTO VINCULADA CASE: ${state.link}`,`RASCUNHO: ${state.draft}`,`STORAGE: ${state.storage}`,`ERRO: ${state.error}`].join('\n');}
function update(p){Object.assign(state,p);state.seq++;state.storage=storageInfo();render();}
function install(){render();update({event:'DIAG PRONTO'});
 const Repo=global.LocalCaseRepository;if(Repo&&Repo.prototype&&!Repo.prototype.__r29){const orig=Repo.prototype.save;Repo.prototype.save=function(caseData){let result;try{result=orig.apply(this,arguments);const raw=localStorage.getItem(this.storageKey);let env=raw?JSON.parse(raw):null;const same=!!(env&&env.case&&caseData&&String(env.case.id||'')===String(caseData.id||''));update({event:'REPOSITORY.SAVE',caseId:caseData&&caseData.id||'-',repo:result&&result.persistent===false?'FALHOU '+short(result.persistence):'PASS',reread:same?'PASS':'FALHOU / CASE DIFERENTE',error:result&&result.persistent===false?short(result.persistence):'-'});return result;}catch(e){update({event:'REPOSITORY.EXCEPTION',repo:'FALHOU',reread:'-',error:short(e.name+': '+e.message)});throw e;}};Repo.prototype.__r29=true;}
 const ES=global.EvidenceStore;if(ES&&ES.prototype&&!ES.prototype.__r29){const orig=ES.prototype.save;ES.prototype.save=async function(ev){try{const r=await orig.apply(this,arguments);let found=false;try{const items=await this.listByCase(String(ev&&ev.case_id||''));found=items.some(x=>String(x.id)===String(ev.id));}catch(_){}update({event:'EVIDENCE.SAVE',caseId:ev&&ev.case_id||state.caseId,photo:found?'PASS':'FALHOU NA RELEITURA',error:found?'-':'IndexedDB gravou mas releitura não encontrou'});return r;}catch(e){update({event:'EVIDENCE.EXCEPTION',photo:'FALHOU',error:short(e.name+': '+e.message)});throw e;}};ES.prototype.__r29=true;}
 const rt=global.auroraRuntime;if(rt&&typeof rt.on==='function'){previousCase=clone(rt.getCase&&rt.getCase());rt.on('case_changed',function(c){const dif=meaningfulDiff(previousCase||{},c||{});previousCase=clone(c);let linked=Array.isArray(c&&c.evidence_groups)?c.evidence_groups.reduce((n,g)=>n+(Array.isArray(g&&g.photos)?g.photos.length:0),0):0;setTimeout(()=>{let draft='-';try{const eng=global.AuroraReportFeature&&global.AuroraReportFeature.engine;const p=eng&&eng.getPersistent?eng.getPersistent(c.id):null;draft=p?('PASS '+short(p.status||'')):'NÃO ENCONTRADO';}catch(e){draft='ERRO '+short(e.name);}update({event:'CASE_CHANGED',caseId:c&&c.id||'-',field:dif.length?dif.join(' | '):'(mudança estrutural)',link:linked>0?`PASS ${linked} ref(s)`:'0 refs',draft});},50);});}
 global.addEventListener('online',()=>update({event:'REDE ONLINE'}));global.addEventListener('offline',()=>update({event:'REDE OFFLINE'}));
}
let tries=0;const t=setInterval(()=>{tries++;if(global.auroraRuntime&&global.LocalCaseRepository&&global.EvidenceStore){clearInterval(t);install();}else if(tries>80){clearInterval(t);render();update({event:'BOOT INCOMPLETO',error:'Runtime/Repository/EvidenceStore indisponível'});}},100);
global.AuroraOfflinePersistenceDiagR29={show(){const e=document.getElementById('aurora-offline-diag-r29');if(e)e.style.display='block';render();},state};
})(window);
