(function(global){
"use strict";
let el=null,timer=null,started=0,onFinish=null,onCancel=null;const MAX_SECONDS=60;
function ensure(){if(el)return el;el=document.createElement('div');el.className='aurora-ai-listen';el.hidden=true;
el.innerHTML='<div class="aurora-ai-listen__backdrop"></div><section class="aurora-ai-listen__panel" role="dialog" aria-modal="true" aria-labelledby="aurora-ai-listen-title"><div class="aurora-ai-listen__brand">✦ AURORA AI</div><div class="aurora-ai-listen__orb" aria-hidden="true"><span class="aurora-ai-listen__mic">🎙</span><i></i><i></i><i></i></div><h2 id="aurora-ai-listen-title">Estou ouvindo...</h2><p class="aurora-ai-listen__hint"></p><div class="aurora-ai-listen__guide"><div class="aurora-ai-listen__guide-title">Conte o que souber sobre:</div><div class="aurora-ai-listen__checks"></div></div><p class="aurora-ai-listen__sub">Pode falar naturalmente. Não precisa seguir a ordem.</p><div class="aurora-ai-listen__time">00:00</div><div class="aurora-ai-listen__actions"><button type="button" class="aurora-ai-listen__cancel">Cancelar</button><button type="button" class="aurora-ai-listen__finish">Finalizar</button></div><div class="aurora-ai-listen__progress" hidden><div class="aurora-ai-listen__spinner"></div><h2>Organizando sua vistoria...</h2><p class="aurora-ai-listen__progress-text">Preparando as informações para preencher os campos.</p><button type="button" class="aurora-ai-listen__cancel aurora-ai-listen__cancel--processing">Cancelar</button></div></section>';
document.body.appendChild(el);el.querySelector('.aurora-ai-listen__finish').addEventListener('click',()=>{if(onFinish)onFinish();});el.querySelectorAll('.aurora-ai-listen__cancel').forEach(b=>b.addEventListener('click',()=>{if(onCancel)onCancel();}));return el;}
function clock(){const s=Math.min(MAX_SECONDS,Math.max(0,Math.floor((performance.now()-started)/1000)));ensure().querySelector('.aurora-ai-listen__time').textContent='00:'+String(s).padStart(2,'0');}
function open(opts){const n=ensure();onFinish=opts&&opts.onFinish||null;onCancel=opts&&opts.onCancel||null;started=performance.now();n.hidden=false;n.dataset.state='listening';n.querySelector('.aurora-ai-listen__hint').textContent=(opts&&opts.hint)||'';const checks=n.querySelector('.aurora-ai-listen__checks');checks.innerHTML='';const items=opts&&Array.isArray(opts.checklist)?opts.checklist:[];n.querySelector('.aurora-ai-listen__guide').hidden=!items.length;items.forEach(label=>{const row=document.createElement('div');row.className='aurora-ai-listen__check';row.innerHTML='<span aria-hidden="true">○</span><span></span>';row.lastElementChild.textContent=label;checks.appendChild(row);});n.querySelector('.aurora-ai-listen__progress').hidden=true;n.querySelector('.aurora-ai-listen__orb').hidden=false;n.querySelector('#aurora-ai-listen-title').hidden=false;n.querySelector('.aurora-ai-listen__hint').hidden=!n.querySelector('.aurora-ai-listen__hint').textContent;n.querySelector('.aurora-ai-listen__guide').hidden=!items.length;n.querySelector('.aurora-ai-listen__sub').hidden=false;n.querySelector('.aurora-ai-listen__time').hidden=false;n.querySelector('.aurora-ai-listen__actions').hidden=false;clock();clearInterval(timer);timer=setInterval(clock,250);document.documentElement.classList.add('aurora-ai-listening-open');}
function processing(text,opts){const n=ensure();if(opts&&opts.onCancel)onCancel=opts.onCancel;clearInterval(timer);timer=null;n.dataset.state='processing';n.querySelector('.aurora-ai-listen__orb').hidden=true;n.querySelector('#aurora-ai-listen-title').hidden=true;n.querySelector('.aurora-ai-listen__hint').hidden=true;n.querySelector('.aurora-ai-listen__guide').hidden=true;n.querySelector('.aurora-ai-listen__sub').hidden=true;n.querySelector('.aurora-ai-listen__time').hidden=true;n.querySelector('.aurora-ai-listen__actions').hidden=true;n.querySelector('.aurora-ai-listen__progress').hidden=false;n.querySelector('.aurora-ai-listen__progress-text').textContent=text||'Preparando as informações para preencher os campos.';}
function update(text){const n=ensure();if(n.dataset.state==='processing'&&text)n.querySelector('.aurora-ai-listen__progress-text').textContent=text;}
function close(){clearInterval(timer);timer=null;onFinish=null;onCancel=null;if(el)el.hidden=true;document.documentElement.classList.remove('aurora-ai-listening-open');}
global.AuroraAiListenOverlay={open,processing,update,close};
})(window);
