(function(global){
'use strict';
const BUILD='DIAG V39 FORENSE R02 — NÃO INVASIVO / FULL CONTRACT TRACE';
const MAX=3000, events=[]; let seq=0;
const now=()=>new Date().toISOString();
const stack=()=>{try{return String(new Error().stack||'').split('\n').slice(2,9).join('\n')}catch(_){return ''}};
function safe(v,d=0){
 if(d>5)return '[depth]'; if(v===undefined)return '__UNDEFINED__'; if(v===null)return null;
 const t=typeof v; if(t==='string')return v.length>1800?v.slice(0,1800)+'…':v; if(t==='number'||t==='boolean')return v; if(t==='function')return `[Function ${v.name||'anonymous'}]`;
 if(v instanceof Element)return {tag:v.tagName,id:v.id||'',cls:String(v.className||''),text:String(v.textContent||'').trim().slice(0,220),dataset:{...v.dataset}};
 if(Array.isArray(v))return v.slice(0,120).map(x=>safe(x,d+1));
 if(t==='object'){const o={};Object.keys(v).slice(0,160).forEach(k=>{try{o[k]=safe(v[k],d+1)}catch(e){o[k]='[error '+e.message+']'}});return o;} return String(v);
}
function customer(c){c=c||{};const f=k=>Object.prototype.hasOwnProperty.call(c,k)?c[k]:'__MISSING__';return {name:f('name'),document:f('document'),phone:f('phone'),email:f('email'),address:f('address'),person_type:f('person_type')};}
function getRT(){return global.auroraRuntime||global.AuroraRuntime||null}
function caseSnap(){try{const rt=getRT(),c=rt&&typeof rt.getCase==='function'?rt.getCase():null;if(!c)return null;return {id:c.id,public_id:c.public_id,profile_id:c.profile_id,service:c.service,status:c.status,created_at:c.created_at,updated_at:c.updated_at,customer:customer(c.customer),snapshot_customer:customer(c.snapshot&&c.snapshot.customer),grounding:{exists:!!c.grounding,keys:c.grounding?Object.keys(c.grounding):[],points:c.grounding&&Array.isArray(c.grounding.points)?c.grounding.points.length:'NOT_ARRAY'}}}catch(e){return {error:e.message}}}
function rtSnap(){const rt=getRT();let active=null;try{active=rt&&rt.steps&&rt.steps[rt.currentIndex]}catch(_){}return {exists:!!rt,ctor:rt&&rt.constructor&&rt.constructor.name,currentIndex:rt&&rt.currentIndex,activeStep:active&&safe(active),stepsType:rt?Object.prototype.toString.call(rt.steps):null,steps:rt&&Array.isArray(rt.steps)?rt.steps.map((s,i)=>({i,id:s&&s.id,title:s&&s.title,type:s&&s.type,module:s&&s.module})):safe(rt&&rt.steps),case:caseSnap()}}
function screenSnap(){const hs=Array.from(document.querySelectorAll('main h1,main h2,.aurora-main h1,.aurora-main h2,[data-screen-title]')).slice(0,8).map(x=>String(x.textContent||'').trim());const side=Array.from(document.querySelectorAll('aside a,aside button,.sidebar a,.sidebar button,[data-step-id]')).slice(0,30).map(x=>({text:String(x.textContent||'').trim().replace(/\s+/g,' ').slice(0,100),id:x.id||'',step:x.dataset&&(x.dataset.stepId||x.dataset.step||'')}));return {headings:hs,sidebar:side,url:location.href}}
function formSnap(){return Array.from(document.querySelectorAll('input,textarea,select')).slice(0,100).map(el=>({tag:el.tagName,type:el.type||'',name:el.name||'',id:el.id||'',field:el.dataset&&(el.dataset.field||el.dataset.agField||''),value:/password/i.test(el.type)?'[redacted]':String(el.value||'').slice(0,900),label:String(el.closest('label')&&el.closest('label').textContent||'').trim().replace(/\s+/g,' ').slice(0,150)}))}
function add(type,data){events.push({n:++seq,ts:now(),type,data:safe(data)});if(events.length>MAX)events.shift();render()}
function storageSnap(){const out=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||'';if(!/ground|report|case|current|project|customer|recent|aurora_reports/i.test(k))continue;const raw=localStorage.getItem(k)||'';let v;try{v=JSON.parse(raw)}catch(_){v=raw.slice(0,1600)};out.push({key:k,len:raw.length,type:Object.prototype.toString.call(v),isArray:Array.isArray(v),value:safe(v)})}return out.slice(0,120)}
function reportContract(){const candidates=[];try{if(global.AuroraReportFeature)candidates.push(['AuroraReportFeature',global.AuroraReportFeature]);if(global.AuroraReportFeature&&global.AuroraReportFeature.engine)candidates.push(['AuroraReportFeature.engine',global.AuroraReportFeature.engine]);if(global.auroraReportEngine)candidates.push(['auroraReportEngine',global.auroraReportEngine]);if(global.AuroraReportEngine)candidates.push(['AuroraReportEngine',global.AuroraReportEngine]);}catch(_){}return candidates.map(([name,o])=>({name,ctor:o&&o.constructor&&o.constructor.name,methods:['list','save','create','get','open','render'].filter(k=>o&&typeof o[k]==='function'),storageKey:o&&o.storageKey}))}
function checkpoint(label,extra){add('CHECKPOINT '+label,{runtime:rtSnap(),screen:screenSnap(),form:formSnap(),reports:reportContract(),extra:extra||null})}
// IMPORTANT: wrapper preserves synchronous return types. It never changes a sync function into Promise.
function wrap(obj,name,label){if(!obj||typeof obj[name]!=='function'||obj[name].__v39r02)return false;const orig=obj[name];function wrapped(){const args=[...arguments];add(label+' BEFORE',{args:safe(args),runtime:rtSnap(),screen:screenSnap(),stack:stack()});let out;try{out=orig.apply(this,args)}catch(e){add(label+' THROW',{message:e.message,stack:e.stack,runtime:rtSnap(),screen:screenSnap()});throw e}add(label+' RETURN',{returnType:Object.prototype.toString.call(out),isArray:Array.isArray(out),isPromise:!!(out&&typeof out.then==='function'),value:safe(out),runtime:rtSnap(),screen:screenSnap()});if(out&&typeof out.then==='function'){out.then(v=>add(label+' RESOLVE',{returnType:Object.prototype.toString.call(v),isArray:Array.isArray(v),value:safe(v),runtime:rtSnap(),screen:screenSnap()}),e=>add(label+' REJECT',{message:e&&e.message,stack:e&&e.stack}));}return out}wrapped.__v39r02=true;wrapped.__original=orig;obj[name]=wrapped;return true}
function install(){
 const rt=getRT(); if(rt)['openStep','saveCurrent','saveCurrentStep','next','previous','resetCase','loadCase','setCase'].forEach(n=>wrap(rt,n,'RUNTIME.'+n));
 const objs=[global.AuroraReportFeature&&global.AuroraReportFeature.engine,global.auroraReportEngine,global.AuroraReportEngine].filter(Boolean);objs.forEach((o,i)=>['list','save','create','get','open','render'].forEach(n=>wrap(o,n,'REPORT['+i+'].'+n)));
 const gs=global.AuroraGroundingShape;if(gs)['open','openFromReport','render','next','finish','save'].forEach(n=>wrap(gs,n,'GROUNDING.'+n));
 const cs=global.AuroraCloudSync;if(cs)['syncSelectedCase','queueCaseForSync','syncCase','restoreCompanyProjectForAdmin'].forEach(n=>wrap(cs,n,'CLOUD.'+n));
 const fr=global.AuroraFormRenderer||global.FormRenderer;if(fr)['render','save','collect','getValues'].forEach(n=>wrap(fr,n,'FORMRENDERER.'+n));
}
const origSet=Storage.prototype.setItem;if(!origSet.__v39r02){Storage.prototype.setItem=function(k,v){if(/ground|report|case|current|project|customer|recent|aurora_reports/i.test(String(k))){let p=v;try{p=JSON.parse(v)}catch(_){}add('STORAGE.setItem',{area:this===localStorage?'local':'session',key:k,len:String(v||'').length,type:Object.prototype.toString.call(p),isArray:Array.isArray(p),value:safe(p),stack:stack()})}return origSet.apply(this,arguments)};Storage.prototype.setItem.__v39r02=true}
global.addEventListener('error',e=>add('WINDOW.ERROR',{message:e.message,filename:e.filename,lineno:e.lineno,colno:e.colno,stack:e.error&&e.error.stack,runtime:rtSnap(),screen:screenSnap()}));
global.addEventListener('unhandledrejection',e=>add('WINDOW.UNHANDLED_REJECTION',{reason:safe(e.reason),stack:e.reason&&e.reason.stack,runtime:rtSnap(),screen:screenSnap()}));
const nativeAlert=global.alert;global.alert=function(msg){add('WINDOW.ALERT',{message:String(msg),runtime:rtSnap(),screen:screenSnap(),stack:stack()});return nativeAlert.apply(this,arguments)};
document.addEventListener('click',e=>{const b=e.target.closest&&e.target.closest('button,a,[data-workflow-next],[data-workflow-previous],[data-service-id],[data-step-id]');if(!b)return;add('DOM.CLICK',{target:safe(b),runtime:rtSnap(),screen:screenSnap(),form:formSnap(),stack:stack()});[0,50,250,800,1600].forEach(ms=>setTimeout(()=>checkpoint('AFTER_CLICK_'+ms+'MS'),ms))},true);
document.addEventListener('input',e=>{const el=e.target;if(!el||!('value'in el))return;const ctx=[el.name,el.id,el.dataset&&el.dataset.field,el.dataset&&el.dataset.agField,el.closest('label')&&el.closest('label').textContent].join(' ');if(/phone|telefone|email|mail/i.test(ctx))add('FORM.IDENTITY_INPUT',{field:safe(el),value:el.value,case:caseSnap(),stack:stack()})},true);
['aurora:case-changed','aurora:case-saved','aurora:report-saved','aurora:report-closed','aurora:cloud-sync','aurora:linked-photo-changed','aurora:edit-report'].forEach(ev=>global.addEventListener(ev,e=>add('EVENT '+ev,{detail:safe(e.detail),runtime:rtSnap(),screen:screenSnap()})));
function dump(){checkpoint('MANUAL_DUMP',{storage:storageSnap()});return JSON.stringify({build:BUILD,generated_at:now(),url:location.href,report_contract:reportContract(),events},null,2)}
function ensureUI(){if(document.getElementById('v39-forensic-r02-tab'))return;const tab=document.createElement('button');tab.id='v39-forensic-r02-tab';tab.textContent='DIAG V39 FORENSE R02';tab.style.cssText='position:fixed;right:8px;top:116px;z-index:2147483647;border:1px solid #ffcc66;border-radius:999px;background:#1b1305;color:#ffcc66;padding:8px 11px;font:700 11px system-ui;cursor:pointer';document.body.appendChild(tab);const box=document.createElement('aside');box.id='v39-forensic-r02-box';box.style.cssText='display:none;position:fixed;right:10px;top:154px;z-index:2147483646;width:min(800px,calc(100vw - 20px));max-height:72vh;overflow:auto;background:#090f18f7;color:#eefaff;border:2px solid #ffcc66;border-radius:14px;padding:12px;font:11px/1.35 Consolas,monospace;box-shadow:0 10px 40px #000a';document.body.appendChild(box);tab.onclick=()=>{box.style.display=box.style.display==='none'?'block':'none';render()}}
function render(){const box=document.getElementById('v39-forensic-r02-box');if(!box||box.style.display==='none')return;const tail=events.slice(-120);box.innerHTML='<div style="position:sticky;top:0;background:#090f18;padding-bottom:8px"><b style="color:#ffcc66;font-size:14px">'+BUILD+'</b><div style="margin-top:7px;display:flex;gap:6px;flex-wrap:wrap"><button id="cp">CHECKPOINT COMPLETO</button><button id="copy">COPIAR DIAG COMPLETO</button><button id="close">FECHAR</button></div><div>Eventos: '+events.length+' / '+MAX+'</div></div>'+tail.map(x=>'<div style="border-top:1px solid #344050;padding:5px 0"><b style="color:#ffcc66">#'+x.n+' '+x.ts+' '+String(x.type).replace(/[&<>]/g,'')+'</b><pre style="white-space:pre-wrap;word-break:break-word;margin:3px 0">'+JSON.stringify(x.data,null,2).replace(/&/g,'&amp;').replace(/</g,'&lt;')+'</pre></div>').join('');box.querySelector('#cp').onclick=()=>checkpoint('BUTTON_FULL',{storage:storageSnap()});box.querySelector('#copy').onclick=async()=>{const t=dump();try{await navigator.clipboard.writeText(t);alert('DIAG V39 FORENSE R02 copiado. Cole no ChatGPT.')}catch(_){prompt('Copie o diagnóstico:',t)}};box.querySelector('#close').onclick=()=>box.style.display='none'}
function boot(){ensureUI();checkpoint('BOOT',{storage:storageSnap()});let tries=0;const t=setInterval(()=>{install();tries++;if(tries%20===0)add('DIAG.HEARTBEAT',{tries,runtime:rtSnap(),screen:screenSnap(),reports:reportContract()});if(tries>360)clearInterval(t)},250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
global.AuroraGroundingForensicV39R02={add,checkpoint,dump,events,build:BUILD};
})(window);
