(function(global){
  "use strict";
  if(global.AuroraSupport)return;
  const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
  const when=value=>new Date(value).toLocaleString("pt-BR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"});
  let client=null,messages=[],overlay=null,button=null,opened=false,lastUnread=-1;
  let nativeNotifyBaselineReady=false;
  const notifiedNativeMessageIds=new Set();
  const diag={mountLastSec:0,badgeLastSec:0};
  global.__auroraSupportDiag=diag;
  function isAdminNotifyMessage(item){return item&&item.sender_role==="admin"&&item.is_automatic!==true}
  function previewBody(body,max=140){const text=String(body||"").replace(/\s+/g," ").trim();if(!text)return"…";return text.length>max?`${text.slice(0,max-1)}…`:text}
  function isSupportConversationOpen(){if(opened)return true;if(overlay&&!overlay.hidden)return true;const native=document.querySelector("[data-native-support-overlay]");return Boolean(native&&!native.hidden)}
  function markNativeNotified(items){(Array.isArray(items)?items:[]).filter(isAdminNotifyMessage).forEach(item=>notifiedNativeMessageIds.add(String(item.id)))}
  function seedNativeNotifyBaseline(items){markNativeNotified(items);nativeNotifyBaselineReady=true}
  async function showNativeNotification(message){const id=String(message.id);notifiedNativeMessageIds.add(id);try{if(global.__AURORA_ANDROID__===true){const bridge=global.AuroraAndroid;if(bridge&&typeof bridge.showSupportNotification==="function")bridge.showSupportNotification(id,"Aurora Chat",previewBody(message.body));return}if("Notification" in global&&Notification.permission==="granted"&&navigator.serviceWorker){const registration=await navigator.serviceWorker.ready;await registration.showNotification("Aurora Chat",{body:previewBody(message.body),tag:`aurora-chat-${id}`,data:{url:"./app.html?open=chat"}})}}catch(error){console.warn("[AURORA CLIENT SUPPORT]",error)}}
  function processNativeNotifications(items){if(!nativeNotifyBaselineReady){seedNativeNotifyBaseline(items);return}if(isSupportConversationOpen()){markNativeNotified(items);return}const fresh=(Array.isArray(items)?items:[]).filter(isAdminNotifyMessage).filter(item=>!item.read_at).filter(item=>!notifiedNativeMessageIds.has(String(item.id)));if(!fresh.length)return;showNativeNotification(fresh[fresh.length-1])}
  function safeProcessNativeNotifications(items){try{processNativeNotifications(items)}catch(error){console.warn("[AURORA CLIENT SUPPORT]",error)}}
  function resolveSupportButton(){if(button&&button.isConnected)return button;button=null;const current=document.querySelector(".aurora-settings-nav [data-support-messages]");if(current){button=current;return button}return null}
  async function rpc(name,args){client=client||global.AuroraCloudSync?.client;if(!client)throw new Error("A conta da Aurora ainda não está disponível.");const {data,error}=await client.rpc(name,args||{});if(error)throw error;return data}
  function ensureOverlay(){if(overlay)return;overlay=document.createElement("div");overlay.className="aurora-support-overlay";overlay.hidden=true;overlay.innerHTML=`<section class="aurora-support-panel" role="dialog" aria-modal="true" aria-label="Mensagens e suporte"><header><div><span>Suporte Aurora</span><h2>Mensagens</h2><p>Envie dúvidas, sugestões ou observações para o administrador.</p></div><button type="button" data-support-close aria-label="Fechar">×</button></header><div class="aurora-support-history" data-support-history></div><form class="aurora-support-form" data-support-form><label for="aurora-support-text">Nova mensagem</label><textarea id="aurora-support-text" maxlength="2000" rows="3" placeholder="Escreva sua mensagem…" required></textarea><div><small data-support-result aria-live="polite"></small><button type="submit">Enviar</button></div></form></section>`;document.body.append(overlay);overlay.querySelector("[data-support-close]").onclick=close;overlay.addEventListener("click",event=>{if(event.target===overlay)close()});overlay.querySelector("[data-support-form]").onsubmit=send}
  function render(){const host=overlay.querySelector("[data-support-history]");host.innerHTML=messages.length?messages.map(item=>`<article class="aurora-support-message ${item.sender_role} ${item.is_automatic?"automatic":""}"><strong>${item.sender_role==="client"?"Você":item.is_automatic?"Aurora · resposta automática":"Aurora"}</strong><p>${esc(item.body)}</p><small>${when(item.created_at)}${item.sender_role==="client"&&item.read_at?" · Lida":""}</small></article>`).join(""):'<div class="aurora-support-empty"><strong>Nenhuma mensagem ainda</strong><span>Quando precisar, escreva para a Aurora por aqui.</span></div>';host.scrollTop=host.scrollHeight;updateBadge()}
  function mount(){diag.mountLastSec+=1;const nav=document.querySelector(".aurora-settings-nav");if(!nav)return false;const existing=nav.querySelector("[data-support-messages]");if(existing){button=existing;if(!existing.hasAttribute("data-support-native")&&!existing.dataset.supportBound){existing.onclick=open;existing.dataset.supportBound="1"}return true}const signout=nav.querySelector("[data-account-signout]");button=document.createElement("button");button.type="button";button.dataset.supportMessages="";button.dataset.supportBound="1";button.innerHTML='<span>💬</span><div><strong>Mensagens e suporte</strong><small>Envie sugestões ou fale com a Aurora</small></div><b>›</b>';button.onclick=open;if(signout)nav.insertBefore(button,signout);else nav.append(button);return true}
  function updateBadge(){diag.badgeLastSec+=1;let btn=resolveSupportButton();if(!btn&&mount())btn=resolveSupportButton();if(!btn)return;const unread=messages.filter(item=>item.sender_role==="admin"&&!item.read_at).length;const label=unread>99?"99+":String(unread);let badge=btn.querySelector(".aurora-support-badge");if(unread){if(lastUnread===unread&&badge&&btn.classList.contains("has-unread"))return;if(!badge){badge=document.createElement("em");badge.className="aurora-support-badge";btn.append(badge)}badge.textContent=label;btn.classList.add("has-unread")}else{if(lastUnread===0&&!badge&&!btn.classList.contains("has-unread"))return;badge?.remove();btn.classList.remove("has-unread")}lastUnread=unread}
  async function refresh(markRead=false){try{messages=await rpc("aurora_support_my_messages")||[];safeProcessNativeNotifications(messages);if(markRead&&messages.some(item=>item.sender_role==="admin"&&!item.read_at)){await rpc("aurora_support_mark_client_read");messages=await rpc("aurora_support_my_messages")||[];lastUnread=-1;safeProcessNativeNotifications(messages)}if(overlay&&!overlay.hidden)render();else updateBadge()}catch(error){if(opened)overlay.querySelector("[data-support-history]").innerHTML=`<div class="aurora-support-empty is-error">${esc(error.message)}</div>`}}
  async function ensureNativePermission(){if(global.__AURORA_ANDROID__===true)return true;if(!("Notification" in global))return false;if(Notification.permission==="granted")return true;if(Notification.permission!=="default")return false;try{return (await Notification.requestPermission())==="granted"}catch(_){return false}}
  async function open(){await ensureNativePermission();ensureOverlay();opened=true;overlay.hidden=false;document.body.classList.add("aurora-support-open");history.pushState({auroraSupport:true},"");overlay.querySelector("[data-support-history]").innerHTML='<div class="aurora-support-empty">Carregando conversa…</div>';await refresh(true)}
  function close(fromHistory=false){if(!overlay||overlay.hidden)return;opened=false;overlay.hidden=true;document.body.classList.remove("aurora-support-open");if(!fromHistory&&history.state?.auroraSupport)history.back()}
  async function send(event){event.preventDefault();const form=event.currentTarget,text=form.querySelector("textarea"),submit=form.querySelector("button"),result=form.querySelector("[data-support-result]"),body=text.value.trim();if(!body)return;submit.disabled=true;result.textContent="Enviando…";try{await rpc("aurora_support_send",{p_body:body});text.value="";result.textContent="Mensagem enviada.";await refresh(false)}catch(error){result.textContent=error.message}finally{submit.disabled=false}}
  global.addEventListener("popstate",()=>{if(opened)close(true)});
  global.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")refresh(opened)});
  setInterval(()=>{if(document.visibilityState==="visible")refresh(opened)},30000);
  function openSupport(){open()}
  global.AuroraSupport={open,refresh,mount,openSupport,ensureNativePermission};
  global.AuroraOpenSupport=openSupport;
})(window);
